import { PermissionKey, RoleType } from '@/types';

export const PERMISSIONS: Record<PermissionKey, { key: PermissionKey; label: string; description: string }> = {
  ORGANIZATION_VIEW: {
    key: 'ORGANIZATION_VIEW',
    label: 'View Organizations',
    description: 'Allows viewing organization details and metadata.',
  },
  ORGANIZATION_CREATE: {
    key: 'ORGANIZATION_CREATE',
    label: 'Create Organizations',
    description: 'Allows creating new child organizations.',
  },
  ORGANIZATION_UPDATE: {
    key: 'ORGANIZATION_UPDATE',
    label: 'Update Organizations',
    description: 'Allows modifying organization settings and details.',
  },
  ORGANIZATION_SUSPEND: {
    key: 'ORGANIZATION_SUSPEND',
    label: 'Suspend Organizations',
    description: 'Allows changing organization status to SUSPENDED, BIN, or REMOVED.',
  },
  USER_VIEW: {
    key: 'USER_VIEW',
    label: 'View Users',
    description: 'Allows viewing user profiles and organization membership rosters.',
  },
  USER_CREATE: {
    key: 'USER_CREATE',
    label: 'Create / Invite Users',
    description: 'Allows creating and inviting new users to an organization.',
  },
  USER_UPDATE: {
    key: 'USER_UPDATE',
    label: 'Update Users',
    description: 'Allows modifying user details and membership roles.',
  },
  USER_DELETE: {
    key: 'USER_DELETE',
    label: 'Remove Users',
    description: 'Allows removing users from an organization.',
  },
  DASHBOARD_VIEW: {
    key: 'DASHBOARD_VIEW',
    label: 'View Dashboard',
    description: 'Allows accessing the VoiceNuvo dashboard workspace.',
  },
  VOICE_PROVIDER_MANAGE: {
    key: 'VOICE_PROVIDER_MANAGE',
    label: 'Manage Voice Provider',
    description: 'Allows configuring and testing voice provider API integrations.',
  },
  AGENT_VIEW: {
    key: 'AGENT_VIEW',
    label: 'View Agents',
    description: 'Allows viewing voice agent configurations.',
  },
  AGENT_MANAGE: {
    key: 'AGENT_MANAGE',
    label: 'Manage Agents',
    description: 'Allows creating, modifying, and deleting voice agents.',
  },
  KNOWLEDGE_BASE_VIEW: {
    key: 'KNOWLEDGE_BASE_VIEW',
    label: 'View Knowledge Base',
    description: 'Allows viewing uploaded knowledge base documents.',
  },
  KNOWLEDGE_BASE_MANAGE: {
    key: 'KNOWLEDGE_BASE_MANAGE',
    label: 'Manage Knowledge Base',
    description: 'Allows uploading, attaching, and deleting knowledge base files.',
  },
  PHONE_NUMBER_VIEW: {
    key: 'PHONE_NUMBER_VIEW',
    label: 'View Phone Numbers',
    description: 'Allows viewing purchased and assigned phone numbers.',
  },
  PHONE_NUMBER_MANAGE: {
    key: 'PHONE_NUMBER_MANAGE',
    label: 'Manage Phone Numbers',
    description: 'Allows searching, purchasing, assigning, and releasing phone numbers.',
  },
  CALL_VIEW: {
    key: 'CALL_VIEW',
    label: 'View Call Logs',
    description: 'Allows viewing organization call history, transcripts, and recordings.',
  },
  CALL_DISPATCH: {
    key: 'CALL_DISPATCH',
    label: 'Dispatch Calls',
    description: 'Allows dispatching outbound voice calls to destination numbers.',
  },
  CALL_MANAGE: {
    key: 'CALL_MANAGE',
    label: 'Manage Calls',
    description: 'Allows managing call settings, syncing call status, and handling webhooks.',
  },
  CAMPAIGN_VIEW: {
    key: 'CAMPAIGN_VIEW',
    label: 'View Campaigns',
    description: 'Allows viewing bulk-call campaigns, progress, and contact-level results.',
  },
  CAMPAIGN_CREATE: {
    key: 'CAMPAIGN_CREATE',
    label: 'Create Campaigns',
    description: 'Allows creating new bulk-call campaigns and draft configurations.',
  },
  CAMPAIGN_MANAGE: {
    key: 'CAMPAIGN_MANAGE',
    label: 'Manage Campaigns',
    description: 'Allows updating campaign settings, concurrency, calling window, and rotation pool.',
  },
  CAMPAIGN_DISPATCH: {
    key: 'CAMPAIGN_DISPATCH',
    label: 'Dispatch Campaigns',
    description: 'Allows starting, pausing, resuming, and canceling bulk-call campaigns.',
  },
  CAMPAIGN_RETRY: {
    key: 'CAMPAIGN_RETRY',
    label: 'Retry Campaign Contacts',
    description: 'Allows triggering retries on eligible unanswered or failed campaign contacts.',
  },
  CAMPAIGN_EXPORT: {
    key: 'CAMPAIGN_EXPORT',
    label: 'Export Campaign Results',
    description: 'Allows exporting campaign contacts and analytics to CSV.',
  },
  LEAD_VIEW: {
    key: 'LEAD_VIEW',
    label: 'View Leads',
    description: 'Allows viewing organization leads, statuses, and CRM activities.',
  },
  LEAD_CREATE: {
    key: 'LEAD_CREATE',
    label: 'Create Leads',
    description: 'Allows creating new leads manually or via public inbound forms.',
  },
  LEAD_MANAGE: {
    key: 'LEAD_MANAGE',
    label: 'Manage Leads',
    description: 'Allows updating lead status, priority, tags, follow-ups, and notes.',
  },
  LEAD_ASSIGN: {
    key: 'LEAD_ASSIGN',
    label: 'Assign Leads',
    description: 'Allows assigning leads to team members or voice agents.',
  },
  LEAD_IMPORT: {
    key: 'LEAD_IMPORT',
    label: 'Import Leads',
    description: 'Allows bulk importing leads from CSV files.',
  },
  LEAD_EXPORT: {
    key: 'LEAD_EXPORT',
    label: 'Export Leads',
    description: 'Allows exporting leads and contact lists to CSV.',
  },
  LEAD_DELETE: {
    key: 'LEAD_DELETE',
    label: 'Delete Leads',
    description: 'Allows archiving or deleting leads.',
  },
  CONTACT_VIEW: {
    key: 'CONTACT_VIEW',
    label: 'View Contacts',
    description: 'Allows viewing contact records and customer identities.',
  },
  CONTACT_MANAGE: {
    key: 'CONTACT_MANAGE',
    label: 'Manage Contacts',
    description: 'Allows creating, updating, and managing customer contact details.',
  },
  INTEGRATION_MANAGE: {
    key: 'INTEGRATION_MANAGE',
    label: 'Manage Integrations',
    description: 'Allows configuring external integrations such as Meta Lead Ads.',
  },
  BILLING_VIEW: {
    key: 'BILLING_VIEW',
    label: 'View Billing',
    description: 'Allows viewing subscription status, wallet balance, and invoices.',
  },
  BILLING_MANAGE: {
    key: 'BILLING_MANAGE',
    label: 'Manage Billing',
    description: 'Allows changing plans, configuring auto top-up, and updating billing profile.',
  },
  BILLING_PAY: {
    key: 'BILLING_PAY',
    label: 'Pay & Top-up',
    description: 'Allows initiating payments, wallet top-ups, and invoice settlements.',
  },
  BILLING_EXPORT: {
    key: 'BILLING_EXPORT',
    label: 'Export Billing Data',
    description: 'Allows exporting invoices, payments, and usage records to CSV.',
  },
  PLAN_VIEW: {
    key: 'PLAN_VIEW',
    label: 'View Plans',
    description: 'Allows viewing subscription plans and pricing rules.',
  },
  PLAN_MANAGE: {
    key: 'PLAN_MANAGE',
    label: 'Manage Plans',
    description: 'Allows platform admins to create and configure plans and usage pricing rules.',
  },
  USAGE_VIEW: {
    key: 'USAGE_VIEW',
    label: 'View Usage',
    description: 'Allows viewing call duration metering and usage charges.',
  },
};

export const ROLE_PERMISSIONS: Record<RoleType, PermissionKey[]> = {
  MAIN_ADMIN: [
    'ORGANIZATION_VIEW',
    'ORGANIZATION_CREATE',
    'ORGANIZATION_UPDATE',
    'ORGANIZATION_SUSPEND',
    'USER_VIEW',
    'USER_CREATE',
    'USER_UPDATE',
    'USER_DELETE',
    'DASHBOARD_VIEW',
    'VOICE_PROVIDER_MANAGE',
    'AGENT_VIEW',
    'AGENT_MANAGE',
    'KNOWLEDGE_BASE_VIEW',
    'KNOWLEDGE_BASE_MANAGE',
    'PHONE_NUMBER_VIEW',
    'PHONE_NUMBER_MANAGE',
    'CALL_VIEW',
    'CALL_DISPATCH',
    'CALL_MANAGE',
    'CAMPAIGN_VIEW',
    'CAMPAIGN_CREATE',
    'CAMPAIGN_MANAGE',
    'CAMPAIGN_DISPATCH',
    'CAMPAIGN_RETRY',
    'CAMPAIGN_EXPORT',
    'LEAD_VIEW',
    'LEAD_CREATE',
    'LEAD_MANAGE',
    'LEAD_ASSIGN',
    'LEAD_IMPORT',
    'LEAD_EXPORT',
    'LEAD_DELETE',
    'CONTACT_VIEW',
    'CONTACT_MANAGE',
    'INTEGRATION_MANAGE',
    'BILLING_VIEW',
    'BILLING_MANAGE',
    'BILLING_PAY',
    'BILLING_EXPORT',
    'PLAN_VIEW',
    'PLAN_MANAGE',
    'USAGE_VIEW',
  ],
  ORG_ADMIN: [
    'ORGANIZATION_VIEW',
    'ORGANIZATION_UPDATE',
    'USER_VIEW',
    'USER_CREATE',
    'USER_UPDATE',
    'USER_DELETE',
    'DASHBOARD_VIEW',
    'VOICE_PROVIDER_MANAGE',
    'AGENT_VIEW',
    'AGENT_MANAGE',
    'KNOWLEDGE_BASE_VIEW',
    'KNOWLEDGE_BASE_MANAGE',
    'PHONE_NUMBER_VIEW',
    'PHONE_NUMBER_MANAGE',
    'CALL_VIEW',
    'CALL_DISPATCH',
    'CALL_MANAGE',
    'CAMPAIGN_VIEW',
    'CAMPAIGN_CREATE',
    'CAMPAIGN_MANAGE',
    'CAMPAIGN_DISPATCH',
    'CAMPAIGN_RETRY',
    'CAMPAIGN_EXPORT',
    'LEAD_VIEW',
    'LEAD_CREATE',
    'LEAD_MANAGE',
    'LEAD_ASSIGN',
    'LEAD_IMPORT',
    'LEAD_EXPORT',
    'LEAD_DELETE',
    'CONTACT_VIEW',
    'CONTACT_MANAGE',
    'INTEGRATION_MANAGE',
    'BILLING_VIEW',
    'BILLING_MANAGE',
    'BILLING_PAY',
    'BILLING_EXPORT',
    'PLAN_VIEW',
    'USAGE_VIEW',
  ],
  EMPLOYEE: [
    'ORGANIZATION_VIEW',
    'USER_VIEW',
    'DASHBOARD_VIEW',
    'AGENT_VIEW',
    'KNOWLEDGE_BASE_VIEW',
    'PHONE_NUMBER_VIEW',
    'CALL_VIEW',
    'CALL_DISPATCH',
    'CAMPAIGN_VIEW',
    'CAMPAIGN_DISPATCH',
    'LEAD_VIEW',
    'LEAD_CREATE',
    'LEAD_MANAGE',
    'CONTACT_VIEW',
  ],
};
